export type Opportunity = {
  id: string;
  symbol: string;
  long_venue: string;
  short_venue: string;
  long_funding_rate: number;
  short_funding_rate: number;
  gross_hourly_rate: number;
  net_hourly_rate: number;
  net_apr_pct: number;
  basis_bps: number;
  capacity_usd: number;
  fee_bps: number;
  entry_fee_bps: number;
  exit_fee_bps: number;
  round_trip_fee_bps: number;
  fee_breakeven_hours: number | null;
  long_order_type: string;
  short_order_type: string;
  long_mark_price: number;
  short_mark_price: number;
  min_open_interest: number;
  observed_at: string;
  eligible: boolean;
  historical_3d_apr_pct?: number | null;
  historical_snapshots_count?: number;
  spread_stability_pct?: number | null;
  funding_rate_source?: string;
  funding_history_latest_cycle?: string | null;
  expected_holding_hours?: number;
  recent_gross_hourly_rate?: number | null;
  recent_net_hourly_rate?: number | null;
  recent_spread_stability_pct?: number | null;
  long_bid_price?: number | null;
  long_ask_price?: number | null;
  short_bid_price?: number | null;
  short_ask_price?: number | null;
};

export type Position = {
  id: string;
  opportunity_id: string;
  symbol: string;
  long_venue: string;
  short_venue: string;
  size_usd: number;
  leg_size_usd?: number | null;
  margin_per_leg_usd?: number | null;
  leverage?: number;
  long_entry_price: number;
  short_entry_price: number;
  entry_basis_bps: number;
  current_long_price?: number | null;
  current_short_price?: number | null;
  current_basis_bps?: number | null;
  funding_pnl_usd: number;
  long_funding_pnl_usd?: number;
  short_funding_pnl_usd?: number;
  settled_funding_pnl_usd?: number;
  settled_long_funding_pnl_usd?: number;
  settled_short_funding_pnl_usd?: number;
  realized_basis_pnl_usd?: number;
  accrued_funding_pnl_usd?: number;
  accrued_long_funding_pnl_usd?: number;
  accrued_short_funding_pnl_usd?: number;
  basis_pnl_usd: number;
  entry_fee_usd: number;
  exit_fee_usd: number;
  fees_usd: number;
  gross_pnl_usd?: number;
  paid_fees_usd?: number;
  net_pnl_usd?: number;
  estimated_close_fee_usd?: number;
  estimated_net_pnl_if_closed_usd?: number;
  estimated_net_proceeds_usd?: number;
  requested_size_usd?: number | null;
  execution_fill_ratio?: number;
  temporary_exposure_usd?: number;
  simulation_run_id?: number | null;
  status: string;
  negative_hours: number;
  opened_at: string;
  updated_at: string;
  open_reason?: string | null;
  closed_at: string | null;
  close_reason: string | null;
  entry_net_apr_pct?: number | null;
  entry_historical_apr_pct?: number | null;
  entry_long_funding_rate?: number | null;
  entry_short_funding_rate?: number | null;
  entry_rate_observed_at?: string | null;
  last_net_apr_pct?: number | null;
  last_long_funding_rate?: number | null;
  last_short_funding_rate?: number | null;
  last_rate_observed_at?: string | null;
};

export type SimulationAccount = {
  id: number;
  initial_balance: number;
  current_balance: number;
  allocated_balance: number;
  total_realized_pnl: number;
  leverage: number;
  run_id?: number | null;
  updated_at: string;
};

export type Settings = {
  id: number;
  min_apr: number;
  min_open_interest: number;
  basis_threshold_bps: number;
  auto_unwind: boolean;
  entry_min_history_snapshots: number;
  entry_min_spread_stability_pct: number;
  negative_hours_to_unwind: number;
  entry_expected_holding_hours: number;
  simulation_min_capital_usd: number;
  simulation_max_drawdown_pct: number;
  alert_webhook_url: string | null;
};

export type Simulation = {
  capital_usd: number;
  holding_days: number;
  leverage: number;
  leg_margin_usd: number;
  leg_notional_usd: number;
  expected_filled_leg_notional_usd: number;
  expected_fill_ratio: number;
  position_notional_usd: number;
  projected_hourly_cashflow_usd: number;
  projected_period_funding_usd: number;
  estimated_round_trip_fees_usd: number;
  estimated_entry_fees_usd: number;
  estimated_exit_fees_usd: number;
  estimated_slippage_usd: number;
  projected_net_profit_usd: number;
  fee_breakeven_hours: number | null;
  projected_return_pct: number;
};
